import type { Metadata } from "next";
import "./globals.css";
import { oswald } from "@/fonts/oswald";
import TopMenu from "@/components/shared/menu/TopMenu";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Cabinet dentaire L'Envolée autour de Montpellier, à Castelnau-le-lèz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="fr">
      <body className={`${oswald.className} relative`}>
          <TopMenu/>
          {children}
          <Footer/>
      </body>
    </html>
  );
}
